import { useMemo, useState, useSyncExternalStore } from 'react';
import { ArrowRight, Check, CircleAlert, RotateCcw, Search, ShieldCheck, ShoppingBag, Sparkles, Star, X } from 'lucide-react';
import { products } from './products'; import { applyFilters, market, visibleProducts } from './store';

export function App({ webmcpSupported }: { webmcpSupported: boolean }) {
  const state = useSyncExternalStore(market.subscribe, market.get); const [cartOpen,setCartOpen]=useState(false); const [query,setQuery]=useState('');
  const visible=visibleProducts(); const compared=useMemo(()=>state.comparedIds.map(id=>products.find(p=>p.id===id)).filter(Boolean),[state.comparedIds]);
  const cartRows=Object.entries(state.cart).map(([id,quantity])=>({item:products.find(p=>p.id===id)!,quantity})); const total=cartRows.reduce((s,r)=>s+r.item.price*r.quantity,0);
  const submit=(e:React.FormEvent)=>{e.preventDefault();applyFilters(query,{});market.set({lastAction:`Showing results for “${query}”`})};
  return <div className="market-app">
    <header className="topbar"><a className="brand" href="#top" aria-label="Buddy Market home"><span className="brand-mark"><i/><i/></span><span>Buddy Market<small>WEBMCP PLAYGROUND</small></span></a><nav aria-label="Primary navigation"><a href="#catalog">Discover</a><a href="#how">How it works</a></nav><button className="cart-button" onClick={()=>setCartOpen(true)}><ShoppingBag/><span>Cart</span><b>{Object.values(state.cart).reduce((a,b)=>a+b,0)}</b></button></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><div className="demo-pill"><span>DEMO</span>No real purchases</div><h1>Thoughtful finds,<br/><em>guided by Buddy.</em></h1><p>A fictional market built to show how websites can offer safe, structured actions to your personal web companion.</p><form className="market-search" onSubmit={submit}><Search/><label className="sr-only" htmlFor="market-query">Search products</label><input id="market-query" value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you looking for?"/><button>Search</button></form><div className="popular"><span>Try:</span>{['a gift under $50','headphones','something for home'].map(value=><button key={value} onClick={()=>{setQuery(value);applyFilters(value,{})}}>{value}</button>)}</div></div>
        <div className="demo-card"><div className="mini-buddy"><span className="mini-face"><i/><i/></span></div><span className="overline">TRY THE DEMO</span><h2>Ask naturally. Stay in control.</h2><blockquote>“Find me a gift under $50 that arrives before Thursday. Compare the best options, but don’t buy anything without asking me.”</blockquote><div className={`webmcp-status ${webmcpSupported?'ready':'needs-flag'}`}>{webmcpSupported?<Check/>:<CircleAlert/>}<div><strong>{webmcpSupported?'Buddy can see this site':'Enable WebMCP for the demo'}</strong><span>{webmcpSupported?'10 structured actions are ready':'Chrome 149+ · enable-webmcp-testing flag'}</span></div></div></div>
      </section>
      <section className="trust-row" id="how"><div><ShieldCheck/><span><strong>Approval by design</strong>Buddy pauses before consequential actions.</span></div><div><Sparkles/><span><strong>Real WebMCP tools</strong>No brittle clicking or page scraping.</span></div><div><RotateCcw/><span><strong>Safe playground</strong>Everything is simulated and resettable.</span></div></section>
      <section className="catalog" id="catalog"><div className="section-head"><div><span className="overline">CURATED FOR THE DEMO</span><h2>{state.query?`Results for “${state.query}”`:'Small things, thoughtfully chosen.'}</h2><p>{visible.length} items · {state.lastAction}</p></div><button className="reset" onClick={()=>{market.reset();setQuery('')}}><RotateCcw/>Reset demo</button></div>
        {compared.length>0&&<section className="compare"><div className="compare-title"><div><span className="overline">BUDDY COMPARED</span><h3>The strongest options, side by side</h3></div><button onClick={()=>market.set({comparedIds:[]})} aria-label="Close comparison"><X/></button></div><div className="compare-grid">{compared.map((item,index)=><article key={item!.id}><span className="rank">{index===0?'BEST MATCH':`OPTION ${index+1}`}</span><strong>{item!.name}</strong><b>${item!.price}</b><small><Star/> {item!.rating} · {item!.deliveryDay}</small></article>)}</div></section>}
        <div className="product-grid">{visible.map(product=><article className={`product-card ${state.comparedIds.includes(product.id)?'selected':''}`} key={product.id}><div className="product-art" style={{'--tone':product.tone} as React.CSSProperties}><span>{product.category}</span><i/><i/></div><div className="product-info"><div className="product-meta"><span>{product.category}</span><span><Star/> {product.rating}</span></div><h3>{product.name}</h3><p>{product.description}</p><div className="attributes">{product.attributes.map(a=><span key={a}>{a}</span>)}</div><div className="product-bottom"><div><strong>${product.price}</strong><small>Arrives {product.deliveryDay}</small></div><button onClick={()=>{market.set({cart:{...state.cart,[product.id]:(state.cart[product.id]??0)+1},lastAction:`Added ${product.name} manually`});setCartOpen(true)}} aria-label={`Add ${product.name} to cart`}><ShoppingBag/></button></div></div></article>)}</div>
        {!visible.length&&<div className="empty-results"><Search/><h3>No exact matches</h3><p>Reset the demo or ask Buddy to try a wider search.</p></div>}
      </section>
    </main>
    <footer><div className="brand"><span className="brand-mark"><i/><i/></span><span>Buddy Market<small>A SAFE WEBMCP DEMO</small></span></div><p>WebMCP gives websites capabilities. Buddy gives those capabilities a face, a voice, and your rules.</p></footer>
    {cartOpen&&<div className="cart-scrim" onMouseDown={e=>{if(e.target===e.currentTarget)setCartOpen(false)}}><aside className="cart-drawer" aria-label="Demo cart"><header><div><span className="overline">DEMO CART</span><h2>Your thoughtful finds</h2></div><button onClick={()=>setCartOpen(false)} aria-label="Close cart"><X/></button></header><div className="cart-content">{cartRows.length===0?<div className="cart-empty"><ShoppingBag/><h3>Your cart is quiet</h3><p>Ask Buddy to find something, or browse the collection.</p></div>:cartRows.map(({item,quantity})=><article key={item.id}><span className="cart-art" style={{background:item.tone}}/><div><strong>{item.name}</strong><span>Qty {quantity} · Arrives {item.deliveryDay}</span></div><b>${(item.price*quantity).toFixed(2)}</b></article>)}</div><div className="cart-summary"><div><span>Total</span><strong>${total.toFixed(2)}</strong></div><p><ShieldCheck/> Demo only — no payment or real order.</p>{state.orderComplete?<div className="order-success"><Check/><strong>Demo order complete</strong><span>No charge was made.</span></div>:<button disabled={!cartRows.length} onClick={()=>market.set({checkoutPrepared:true,lastAction:'Checkout prepared manually'})}>Review demo checkout<ArrowRight/></button>}</div></aside></div>}
  </div>;
}
