import { registerTools, type RegisterableTool } from '@buddy/webmcp-bridge';
import { products } from './products'; import { applyFilters, market, visibleProducts, weekdayOrder } from './store';
const objectSchema=(properties:Record<string,unknown>,required:string[]=[]):Record<string,unknown>=>({type:'object',properties,required,additionalProperties:false});
const text=(description:string)=>({type:'string',description}); const number=(description:string)=>({type:'number',description});
function result(message:string,data:unknown={}){return {message,data}}
const tools:RegisterableTool[]=[
 {name:'search_items',title:'Search items',description:'Search the marketplace catalog by product need, category, or descriptive keywords. Use this to begin a product discovery goal.',inputSchema:objectSchema({query:text('A concise product need or category, such as gift or headphones.')},['query']),annotations:{readOnlyHint:true},execute:({query})=>{const found=applyFilters(String(query??''),{});market.set({lastAction:`Buddy found ${found.length} matching items`});return result(`Found ${found.length} matching items.`,{count:found.length,items:found.slice(0,10)})}},
 {name:'get_item_details',title:'Get item details',description:'Get complete details for one marketplace item by its ID.',inputSchema:objectSchema({itemId:text('The marketplace item ID.')},['itemId']),annotations:{readOnlyHint:true},execute:({itemId})=>{const item=products.find(p=>p.id===itemId);if(!item)throw new Error('Item not found');return result(`Retrieved details for ${item.name}.`,item)}},
 {name:'filter_items',title:'Filter items',description:'Narrow the current marketplace results by maximum price, minimum rating, and latest acceptable delivery weekday.',inputSchema:objectSchema({maxPrice:number('Maximum price in US dollars.'),minRating:number('Minimum customer rating from 0 to 5.'),deliveryBy:text('Latest delivery weekday, such as Thursday.')}),annotations:{readOnlyHint:true},execute:({maxPrice,minRating,deliveryBy})=>{const filters={...(typeof maxPrice==='number'?{maxPrice}:{}),...(typeof minRating==='number'?{minRating}:{}),...(typeof deliveryBy==='string'&&weekdayOrder[deliveryBy.toLowerCase()]?{deliveryOrder:weekdayOrder[deliveryBy.toLowerCase()]}:{})};const found=applyFilters(market.get().query,filters);market.set({lastAction:`Buddy narrowed the list to ${found.length} items`});return result(`Narrowed the list to ${found.length} items.`,{count:found.length,items:found.slice(0,10)})}},
 {name:'compare_items',title:'Compare items',description:'Compare the strongest currently visible items by rating, price, delivery, and attributes.',inputSchema:objectSchema({limit:number('Number of top items to compare, from 2 to 4.')}),annotations:{readOnlyHint:true},execute:({limit})=>{const count=Math.max(2,Math.min(4,Number(limit)||3));const choices=visibleProducts().slice(0,count);market.set({comparedIds:choices.map(p=>p.id),lastAction:`Buddy compared the top ${choices.length}`});return result(`Compared the top ${choices.length} options.`,choices)}},
 {name:'add_to_cart',title:'Add to cart',description:'Add a specific item, or the best currently visible option, to the temporary demo cart. This changes cart state but does not purchase anything.',inputSchema:objectSchema({itemId:text('Optional item ID.'),selection:text('Use best to select the highest-rated visible item.')}),execute:({itemId,selection})=>{const item=products.find(p=>p.id===itemId)||(selection==='best'?visibleProducts()[0]:undefined);if(!item)throw new Error('No matching item is available');const cart={...market.get().cart,[item.id]:(market.get().cart[item.id]??0)+1};market.set({cart,lastAction:`Buddy added ${item.name} to the cart`,checkoutPrepared:false});return result(`Added ${item.name} to the demo cart.`,{item,cart})}},
 {name:'remove_from_cart',title:'Remove from cart',description:'Remove one item from the temporary demo cart.',inputSchema:objectSchema({itemId:text('The item ID to remove.')},['itemId']),execute:({itemId})=>{const cart={...market.get().cart};delete cart[String(itemId)];market.set({cart,lastAction:'Buddy updated the cart',checkoutPrepared:false});return result('Removed the item from the demo cart.',{cart})}},
 {name:'get_cart',title:'Get cart',description:'Read the current temporary demo cart and its total.',annotations:{readOnlyHint:true},execute:()=>{const items=Object.entries(market.get().cart).map(([id,quantity])=>({item:products.find(p=>p.id===id),quantity}));const total=items.reduce((sum,row)=>sum+(row.item?.price??0)*row.quantity,0);return result(`The demo cart contains ${items.length} items totaling $${total.toFixed(2)}.`,{items,total})}},
 {name:'set_delivery_preference',title:'Set delivery preference',description:'Set the preferred delivery speed for the demo cart.',inputSchema:objectSchema({preference:{type:'string',enum:['Standard','Express'],description:'Preferred demo delivery speed.'}},['preference']),execute:({preference})=>{market.set({deliveryPreference:String(preference),lastAction:`Delivery set to ${preference}`});return result(`Delivery preference set to ${preference}.`)}},
 {name:'prepare_checkout',title:'Prepare checkout',description:'Prepare a review of the demo order without placing it or charging money.',annotations:{readOnlyHint:true},execute:()=>{market.set({checkoutPrepared:true,lastAction:'Buddy prepared the demo checkout'});return result('The demo checkout is ready for review. No purchase has occurred.')}},
 {name:'checkout',title:'Complete demo checkout',description:'Complete a simulated checkout. No payment is collected and no real purchase occurs.',execute:()=>{if(!Object.keys(market.get().cart).length)throw new Error('The demo cart is empty');market.set({orderComplete:true,lastAction:'Demo order completed — no charge'});return result('Demo checkout complete. No real purchase or charge occurred.',{demo:true,orderId:'BUDDY-DEMO-2048'})}},
];
export const installWebMCPTools=()=>registerTools(tools);
